var data = { 
    home: "Home", 
    receipes :"Receipes",
    appetizer: "Appetizer",
    maincourse: "Main course",
    dessert: "Dessert",
    snack: "Snack",
    addrecipe: "Add receipe",
    yprofile: "My profile",
    login: "Log in",
    signup: "Sign up",
    logout: "Log out",
    aboutus: "About us",
    language: "Language",
    sortrat: "Sort by rating",
    sortdif: "Sort by difficulty",
    search: "Search",
    best3: "The best 3 recipes",
    ourpartners: "Our partners:",
    usernamepro: "Username:",
    whoare: "Who we are and what we do?",
    ourgoal: "Our goal is to help u make some cool food",
    username: "Username",
    password: "Password",
    loginbut: "Log In",
    callus: "Our phone number: (+381) 60 12345 6789",
    beginner: "Beginner",
    intermediate: "Intermediate",
    advanced: "Advanced",
    recipename: "Recipe name",
    cooktime: "Cooking time (mins)",
    shortdesc: "Short description",
    ingredients: "Ingredients",
    instructions: "Instructions",
    myrecipes: "My recipes:",
    delete: "Delete",
    cooktime: "Cooking time:",
    writearew: "Write a review",
    reviews: "Reviews:",
    myreviews:"My reviews:",
    others: "Others prepared like this:"

}
 