var data = { 
    home: "Početna", 
    receipes:"Recepti",
    appetizer: "Predjelo",
    maincourse: "Glavno jelo",
    dessert: "Dezert",
    snack: "Užina",
    addrecipe: "Dodaj recept",
    myprofile: "Moj profil",
    login: "Prijavi se",
    signup: "Registruj se",
    logout: "Odjavi se",
    aboutus: "O nama",
    language: "Jezik",
    sortrat: "Ocene sort",
    sortdif: "Težina sort",
    search: "Pretraži",
    best3: "Najbolja 3 recepta",
    ourpartners: "Naši saradnici:",
    usernamepro: "Korisničko ime:",
    whoare: "Ko smo mi i čime se bavimo?",
    ourgoal: "Mi smo vaš kulinarski online kutak i jedini cilj nam je da Vam pomognemo u pripremenju ukusne hrane",
    username: "Korisničko ime",
    password: "Lozinka",
    loginbut: "Prijavi se",
    callus: "Naš broj telefona: (+381) 60 12345 6789",
    beginner: "Početni",
    intermediate: "Srednji",
    advanced: "Napredni",
    recipename: "Naziv recepta",
    cooktime: "Vreme kuvanja (minuti)",
    shortdesc: "Kratak opis",
    ingredients: "Sastojci",
    instructions: "Instrukcije",
    myrecipes: "Moji recepti:",
    delete: "Obriši",
   
    
}