var data = { 
    home: "Početna", 
    receipes:"Recepti",
    appetizer: "Predjelo",
    maincourse: "Glavno jelo",
    desert: "Dezert",
    snack: "Užina",
    addrecipe: "Dodaj recept",
    myprofile: "Moj profil",
    login: "Prijavi se",
    signup: "Registruj se",
    logout: "Odjavi se",
    aboutus: "O nama",
    language: "Jezik",
    sortrat: "Ocene sort",
    sortdif: "Težina sort",
    search: "Pretraži",
    best3: "Najbolja 3 recepta",
    ourpartners: "Naši saradnici:",
    usernamepro: "Korisničko ime:",
    
}